In [9]:
df1.columns

Index(['Unnamed: 0', 'First Name', 'Last Name', 'Gender', 'Age', 'CNIC',
       'Applied Course', 'Domicile', 'Email', 'Phone number',
       'What best describes your access to a computer?',
       'Academic Concentration', 'CGPA/Final Average GPA',
       'Highest level of Education', 'Training district', 'Score',
       'Initial Screening Percentage', 'Points Scored Screning Test',
       'Screening Test Percentage', 'Agreegate Percentage', 'Submitted At',
       'Allocated District', 'Status', 'Batch', 'Internal Assessments',
       'Certifications', 'Job Placement', 'Comments', 'Unnamed: 28',
       'Unnamed: 29', 'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32',
       'Unnamed: 33', 'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36',
       'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40',
       'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43'],
      dtype='object')

In [10]:
df1.dtypes

Unnamed: 0                                         object
First Name                                         object
Last Name                                          object
Gender                                             object
Age                                                 int64
CNIC                                                int64
Applied Course                                     object
Domicile                                           object
Email                                              object
Phone number                                      float64
What best describes your access to a computer?     object
Academic Concentration                             object
CGPA/Final Average GPA                             object
Highest level of Education                         object
Training district                                  object
Score                                               int64
Initial Screening Percentage                      float64
Points Scored Screning Test                       float64
Screening Test Percentage                          object
Agreegate Percentage                              float64
Submitted At                                      float64
Allocated District                                float64
Status                                             object
Batch                                              object
Internal Assessments                              float64
Certifications                                    float64
Job Placement                                     float64
Comments                                          float64
Unnamed: 28                                       float64
Unnamed: 29                                       float64
Unnamed: 30                                       float64
Unnamed: 31                                       float64
Unnamed: 32                                       float64
Unnamed: 33                                       float64
Unnamed: 34                                       float64
Unnamed: 35                                       float64
Unnamed: 36                                       float64
Unnamed: 37                                       float64
Unnamed: 38                                       float64
Unnamed: 39                                       float64
Unnamed: 40                                       float64
Unnamed: 41                                       float64
Unnamed: 42                                       float64
Unnamed: 43                                       float64
dtype: object

In [12]:
df1.drop('Unnamed: 0',axis=1,inplace=True)
df1.head()

,First Name,Last Name,Gender,Age,CNIC,Applied Course,Domicile,Email,Phone number,What best describes your access to a computer?,Academic Concentration,CGPA/Final Average GPA,Highest level of Education,Training district,Score,Initial Screening Percentage,Points Scored Screning Test,Screening Test Percentage,Agreegate Percentage,Submitted At,Allocated District,Status,Batch,Internal Assessments,Certifications,Job Placement,Comments,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,Unnamed: 33,Unnamed: 34,Unnamed: 35,Unnamed: 36,Unnamed: 37,Unnamed: 38,Unnamed: 39,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43
0,Waseem,Akram,Male,29,1710303501939,AWS,Charsadda,Waseemhse999@gmail.com,0.0,Having own laptop,Engineering,Below 2.5,Bachelor / Other,Peshawar,43,0.286667,6.0,15%,0.218333,43700.185984,NaN,13-Not Shortlisted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Asifa khan,Asifa,Female,23,135031253685,Azure MCSD,Abbottabad,Asifakhan392@gmail.com,351370.0,Having own laptop,Other,Between 2.5 and 3.0,Master,Abbottabad,41,0.273333,NaN,NaN,0.136667,43705.700787,NaN,13-Not Shortlisted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,nadia,khattak,Female,23,1730183562728,Azure MCSD,Peshawar,naskkhattak@gmail.com,312917897.0,Having own laptop,Computer Science/IT,Above 3.0,Bachelor / Other,Peshawar,99,0.660000,20.0,50%,0.580000,43711.566713,NaN,3-Appears in Technical Test,ADS-AZ-C1-B1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Muhammad,Ayaz,Male,21,2160254263717,Azure MCSD,Orakzai,Ayazmuhammad653@gmail.com,312969693.0,No regular access to computer,Other,Below 2.5,Bachelor / Other,Peshawar,-17,-0.113333,NaN,NaN,-0.056667,43703.283935,NaN,13-Not Shortlisted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Muhammad waqas khan,Khan,Male,26,1110111156401,Azure MCSD,Bannu,Wk506751@gamil.com,332332368.0,use computer at school/ university,Computer Science/IT,Below 2.5,Master,Peshawar,29,0.193333,NaN,NaN,0.096667,43698.753009,NaN,13-Not Shortlisted,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN